######################################################
# _____  _____                                       #
# |  __ \|  __ \                                     #
# | |__) | |  | |                                    #
# |  _  /| |  | |                                    #
# | | \ \| |__| |                                    #
# |_|  \_\_____/                                     #
#                                                    #
# RestrictedDimensions by Andre_601                  #
#                                                    #
# GitHub:                                            #
#   https://github.com/Andre601/RestrictedDimensions #
######################################################
#
# Feel free to disable the RD-banner (like above), if you want to keep the console more clean.
#
ShowBanner: true
#
# Should the plugin log denied access in the console?
# The message would be "[RestrictedDimensions] Player {player} was denied access to the dimension {dimension_name}"
#
LogDeniedAccess: true
#
# Message send when the player lacks the permission restricteddimensions.enter.{dimension} to enter {dimension}.
#
# Placeholder:
#   %dimension%  ->  The name of the dimension the player was denied access to.
#
NoPermission: '&cYou don''t have permissions, to enter the dimension %dimension%!'