name: RestrictedNether
version: 1.0.1
author: Andre_601

main: com.andre601.restrictednether.RestrictedNether

api-version: 1.13

permissions:
  restrictednether.allow:
    description: Allows you to access the nether.
    default: op