name: RestrictedDimensions
version: ${project.version}
authors:
- Andre_601

main: com.andre601.restricteddimensions.RestrictedDimensions

api-version: '1.13'
softdepend:
- PlaceholderAPI

permissions:
  restricteddimensions.bypass:
    description: Allows you to bypass any restrictions of the plugin.
    default: op